### ISSUE TITLE
semantic-ui styles don't work

### ISSUE THREAD

**Issue by madCoder24** [meltedspark/electron-angular-native#24]
First, great work on this project.

It doesn't seem that any external stylesheets are being applied. I have installed semantic-ui with NPM and have added the appropriate css file to the 'styles' array within the file webpack.config.dev.js. Things seem to be compiling correctly as my application loads but there are no styles are anything loaded.

```
entry: {
        main: [
            "./src/main.ts"
        ],
        polyfills: [
            "./src/polyfills.ts"
        ],
        styles: [
            "./node_modules/semantic-ui/dist/semantic.css",
            "./src/styles.scss"
        ]
    },
```

Is there an example you can provide to include external stylesheets or to even have the global styles working correctly? Maybe I am missing something simple.

**Comment by meltedspark** [comment]
Could you provide a fork with repro?

**Comment by meltedspark** [comment]
Have you seen [this](https://dev.to/chiangs/integrating-semantic-ui-to-an-angular-cli-project-20el)? It seems that you need to include `semantic.min.js` in your scripts. Have you done that?

**Comment by madCoder24** [comment]
Yes, I have added the scripts and also made sure jQuery was accessible. I will try to get a repo up that reproduces it as soon as possible for you to investigate.

**Comment by madCoder24** [comment]
It looks like I was able to fix this by putting the link tag referencing the semantic-ui styles into the index.html file. I will still create the repository for you to investigate why it wasn't working within the 'styles' array if you still want it?

**Comment by meltedspark** [comment]
Yep it would be great, thanks

**Comment by meltedspark** [comment]
Will reopen once reproduction is provided
