### ISSUE TITLE
replace node-ffi with node-ffi-napi

### ISSUE THREAD

**Issue by cynx** [meltedspark/electron-angular-native#58]
node-ffi has not been in active development for a while and there are growing concerns about the future of the project. Would recommend to replace the package with more active repo node-ffi-napi.
This would also solve the node 9 support issue.

https://github.com/node-ffi-napi/node-ffi-napi

**Comment by meltedspark** [comment]
Good point, will look into that. PR is welcome though. For sure it will be much faster. 
Also, N-API is supported starting from `Node 8` bit since it is also the minimal required version for relevant version of Angular it should he fine.

**Comment by meltedspark** [comment]
Another option is [fastcall](https://github.com/cmake-js/fastcall#readme)
